name: roti
version: '0.1'
summary: snap to controlle my robotics stuff
description: |
  Nothing here yet!

grade: devel
confinement: devmode

parts:
  roti:
    source: https://github.com/FelixMo42/roti.git
    plugin: python
    python-version: python3

apps:
  roti-start:
    command: bin/roti